services:
  # DATABASE SERVICE (MongoDB)
  mongodb:
    image: mongo:latest
    container_name: secure-note-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    restart: unless-stopped

  # BACKEND SERVICE (Express.js)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: secure-note-backend
    ports:
      - "5002:5002"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
    command: node server.js
    restart: unless-stopped

  # FRONTEND SERVICE (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: secure-note-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    command: npm run start
    restart: unless-stopped

volumes:
  mongodb_data: